#!/bin/bash

if [ -z $1 ]; then
    echo 'you need url.'
    exit
fi

port=22
if [ ! -z $2 ]; then
    port=$2
fi

echo $*

brew services start tor
sudo proxychains4 nmap -sT -PN -n -sV -p $port $1
brew services stop tor
